### ISSUE TITLE
Constructors featuring controlpoint values are not parsed correctly

### ISSUE THREAD

**Issue by VikingScientist** [TheBB/lrsplines-python#33]
``` python
import lrspline as lr

srf = lr.LRSplineSurface(2,2,2,2, [0,0,1,1], [0,0,1,1], [[3,4], [2,3], [4,10], [1,2]])
for func in srf.basis:
    print(func.controlpoint)
```
gives the following output
```
[0. 0.]
[1. 0.]
[0. 1.]
[1. 1.]
```
Where I expect it to produce the 4 given controlpoints `[3,4], [2,3], [4,10]` and `[1,2]`

**Comment by TheBB** [comment]
Thanks, fixed in https://github.com/TheBB/lrsplines-python/commit/0cd03995dd3f1cf7e2bb665f6636bbd113ee4ec2
