### ISSUE TITLE
Insufficient installation instructions

### ISSUE THREAD

**Issue by kmokstad** [TheBB/lrsplines-python#9]
When I try to install this, I only get:
```
kmo@kmoPC7510:~/libs/lrsplines-python.git$ pip3 install
Traceback (most recent call last):
  File "/home/kmo/.local/bin/pip3", line 7, in <module>
    from pip._internal import main
ImportError: No module named 'pip._internal'
```
so clearly I'm not doing it right. But since I'm only a novice python user I have no idea what.
Could the installation instruction have been a little bit more descriptive?

**Comment by TheBB** [comment]
This should be better now. `pip install lrsplines` should suffice.
